import type { ConfigView, NotificationView, Snapshot } from "./types";

// Illustrative data shown before the dashboard connects to a live daemon. It is
// always badged as a demo so it can never be mistaken for real protection.

const NOW = "2026-05-29T17:00:00Z";
const A_MINUTE_AGO = "2026-05-29T16:59:00Z";
const MINUTES_AGO = "2026-05-29T16:53:00Z";
const AN_HOUR_AGO = "2026-05-29T16:00:00Z";

export const demoConfig: ConfigView = {
  path: "demo",
  mode: "alert",
  usage_enabled: true,
  warn_turn_tokens: 1_000_000,
  kill_turn_tokens: 3_000_000,
  usage_window_seconds: 900,
  usage_scan_seconds: 5,
  lookback_seconds: 86_400,
  process_warn_seconds: 5_400,
  process_kill_seconds: 7_200,
  ack_extension_seconds: 1_800,
  local_notifications: true,
  escalate_supervised: false,
  agents: [
    { id: "codex-cli", label: "Codex CLI", family: "codex", kind: "process", terminates: true, description: "Codex CLI worker" },
    { id: "claude-code", label: "Claude Code", family: "claude", kind: "process", terminates: true, description: "Claude Code worker" },
    { id: "codex-desktop", label: "Codex Desktop", family: "codex", kind: "app", terminates: false, description: "watch-only desktop app" },
  ],
};

export const demoNotifications: NotificationView = {
  enabled: true,
  available: true,
  status: "ready",
  message: "Demo notifications are ready.",
};

export const demoSnapshot: Snapshot = {
  overview: {
    mode: "watch",
    status: "ACTION",
    message: "1 over the kill line",
    working: 3,
    warn: 1,
    kill: 1,
    busiest_turn_tokens: 3_300_000,
    last_scan: NOW,
    sources: [
      { provider: "codex", files: 12, events: 340 },
      { provider: "claude", files: 8, events: 210 },
    ],
    changes: {
      new_sessions: 0,
      sessions_with_new_turns: 1,
      tokens_added: 62_000,
      new_alerts: 0,
      agents_started: 0,
      agents_ended: 0,
      source_errors: 0,
    },
    capabilities: {
      platform: "demo",
      notifications: { available: true, status: "ready", message: "notifications ready" },
      process_capture: { available: true, status: "ready", message: "process capture available" },
      process_identity: { available: true, status: "ready", message: "identity evidence available" },
      enforcement: { available: false, status: "disabled", message: "watch mode never stops processes" },
    },
  },
  agents: [
    { id: "claude-code", provider: "claude", label: "Claude Code", status: "working", pid: 4242, process_started_at: AN_HOUR_AGO, running_for_seconds: 3600, project: "gradient", cwd: "/Users/you/dev/gradient", session_key: "claude:gradient", turn_tokens: 1_400_000, explanation: "Over your warn line this turn." },
    { id: "codex-cli", provider: "codex", label: "Codex CLI", status: "working", pid: 5310, process_started_at: A_MINUTE_AGO, running_for_seconds: 240, project: "curb", cwd: "/Users/you/dev/curb", session_key: "codex:curb", turn_tokens: 320_000, explanation: "Working." },
  ],
  sessions: [
    {
      key: "codex:olympus",
      id: "olympus",
      provider: "codex",
      status: "working",
      alert: "kill",
      can_stop: false,
      can_acknowledge: true,
      project: "olympus",
      cwd: "/Users/you/dev/olympus",
      models: ["gpt-5-codex"],
      turn_tokens: 3_300_000,
      turn_context_tokens: 3_600_000,
      total_tokens: 8_100_000,
      calls: 52,
      last_activity_at: NOW,
      pid: 7731,
      process_started_at: A_MINUTE_AGO,
      owner: "you",
      executable: "/Applications/Codex.app/Contents/Resources/codex",
      explanation:
        "Over your kill line, but this is a watch-only desktop app that supervises the task and would respawn it — Curb can warn but not stop it.",
    },
    {
      key: "claude:gradient",
      id: "gradient",
      provider: "claude",
      status: "working",
      alert: "warn",
      can_stop: false,
      can_acknowledge: true,
      project: "gradient",
      cwd: "/Users/you/dev/gradient",
      models: ["claude-opus-4-8"],
      turn_tokens: 1_400_000,
      turn_context_tokens: 1_650_000,
      total_tokens: 4_200_000,
      calls: 38,
      last_activity_at: NOW,
      pid: 4242,
      process_started_at: AN_HOUR_AGO,
      owner: "you",
      executable: "/usr/local/bin/claude",
      explanation: "Over your warn line this turn.",
    },
    {
      key: "codex:curb",
      id: "curb",
      provider: "codex",
      status: "working",
      alert: "ok",
      can_stop: false,
      can_acknowledge: false,
      project: "curb",
      cwd: "/Users/you/dev/curb",
      models: ["gpt-5-codex"],
      turn_tokens: 320_000,
      turn_context_tokens: 410_000,
      total_tokens: 1_900_000,
      calls: 21,
      last_activity_at: NOW,
      pid: 5310,
      process_started_at: A_MINUTE_AGO,
      owner: "you",
      executable: "/usr/local/bin/codex",
      explanation: "Working, within your limits.",
    },
    {
      key: "codex:daybook",
      id: "daybook",
      provider: "codex",
      status: "idle",
      alert: "ok",
      can_stop: false,
      can_acknowledge: false,
      project: "daybook",
      cwd: "/Users/you/dev/daybook",
      models: ["gpt-5-codex"],
      turn_tokens: 55_000,
      turn_context_tokens: 120_000,
      total_tokens: 2_300_000,
      calls: 64,
      last_activity_at: MINUTES_AGO,
      explanation: "Idle between turns.",
    },
  ],
  turns: [
    {
      id: "turn-demo-2",
      request_id: "req-demo-2",
      session_key: "codex:olympus",
      session_id: "olympus",
      provider: "codex",
      at: NOW,
      model: "gpt-5.5",
      input_tokens: 1_200_000,
      cached_input_tokens: 180_000,
      cache_creation_input_tokens: 25_000,
      output_tokens: 240_000,
      reasoning_output_tokens: 90_000,
      total_tokens: 1_555_000,
      spent_tokens: 1_375_000,
      cumulative_tokens: 3_300_000,
      source: "codex usage log",
    },
  ],
};
