import type { AlertView, ConfigView, Snapshot } from "./types";

const now = new Date().toISOString();

export const demoSnapshot: Snapshot = {
  overview: {
    mode: "alert",
    action: "notify only; never kill",
    status: "WATCH",
    message: "usage is over a warning threshold",
    active_agents: 4,
    active_sessions: 2,
    warning_sessions: 1,
    stop_sessions: 0,
    idle_high_sessions: 1,
    window_tokens: 632_000,
    lookback_tokens: 42_350_000,
    last_scan: now,
    changes: {
      new_sessions: 1,
      sessions_with_new_turns: 1,
      tokens_added: 620_000,
      new_alerts: 1,
      agents_started: 0,
      agents_ended: 0,
      source_errors: 0,
    },
    sources: [
      { provider: "codex", files: 27, events: 2308 },
      { provider: "claude", files: 3, events: 10 },
    ],
    capabilities: {
      platform: "demo",
      notifications: { available: true, status: "ready", message: "demo notifications are ready" },
      process_capture: { available: true, status: "ready", message: "4 processes captured" },
      process_identity: { available: true, status: "ready", message: "4 processes with identity evidence" },
      enforcement: { available: false, status: "disabled", message: "current mode will not terminate processes" },
    },
  },
  agents: [
    {
      id: "codex-desktop-worker",
      provider: "codex",
      label: "Codex Desktop Worker",
      state: "warn",
      activity_state: "spending",
      process_state: "running",
      usage_state: "warn",
      action_state: "acknowledge",
      actionable: false,
      pid: 91226,
      process_started_at: now,
      running_for_seconds: 1640,
      project: "curb",
      cwd: "/Users/phaedrus/Development/curb",
      matched_by: ["process_name:codex", "command_regex:app-server", "command_regex:stdio"],
      confidence: 170,
      latest_session_id: "019e4bf7-6412-748a-b900-1df04db3f220",
      latest_turn_tokens: 620_000,
      window_tokens: 620_000,
      explanation: "latest checkpoint over warning threshold",
    },
    {
      id: "claude-code",
      provider: "claude",
      label: "Claude Code",
      state: "idle",
      activity_state: "idle",
      process_state: "running",
      usage_state: "quiet",
      action_state: "none",
      actionable: false,
      pid: 18548,
      process_started_at: now,
      running_for_seconds: 9400,
      project: "daybook",
      cwd: "/Users/phaedrus/Documents/daybook",
      matched_by: ["command_regex:claude"],
      confidence: 55,
      latest_session_id: "ce35bba6-88fb-40b7-a6be-c57fd389ba6a",
      latest_turn_tokens: 55_323,
      explanation: "process is running; correlated session is not currently spending",
    },
    {
      id: "codex-desktop-worker",
      provider: "codex",
      label: "Codex Desktop Worker",
      state: "running",
      activity_state: "idle",
      process_state: "running",
      usage_state: "quiet",
      action_state: "none",
      actionable: false,
      pid: 96450,
      process_started_at: now,
      running_for_seconds: 740,
      project: "thinktank",
      cwd: "/Users/phaedrus/.codex/worktrees/06d3/thinktank",
      matched_by: ["process_name:codex", "command_regex:app-server"],
      confidence: 170,
      explanation: "process is running with no correlated usage",
    },
    {
      id: "codex-cli",
      provider: "codex",
      label: "Codex CLI",
      state: "watch-only",
      activity_state: "idle",
      process_state: "watch-only",
      usage_state: "stop",
      action_state: "blocked",
      actionable: false,
      pid: 37129,
      process_started_at: now,
      running_for_seconds: 2800,
      project: "gradient",
      cwd: "/Users/phaedrus/Development/gradient",
      matched_by: ["process_name:codex"],
      confidence: 80,
      latest_turn_tokens: 3_200_000,
      window_tokens: 3_200_000,
      explanation: "usage crossed threshold, but matched agent is watch-only; Curb will not stop desktop apps",
    },
  ],
  sessions: [
    {
      key: "codex:019e4bf7-6412-748a-b900-1df04db3f220",
      id: "019e4bf7-6412-748a-b900-1df04db3f220",
      provider: "codex",
      state: "warn",
      activity_state: "spending",
      process_state: "running",
      usage_state: "warn",
      action_state: "acknowledge",
      actionable: false,
      project: "curb",
      cwd: "/Users/phaedrus/Development/curb",
      models: ["gpt-5.3-codex"],
      last_seen_at: now,
      last_usage_at: now,
      calls: 33,
      latest_turn_tokens: 620_000,
      window_tokens: 620_000,
      total_tokens: 3_500_000,
      correlated_agent_id: "codex-desktop-worker",
      correlated_pid: 91226,
      correlated_process_started_at: now,
      correlation_reason: "provider+cwd",
      correlation_score: 125,
	      confidence: 170,
	      matched_by: ["process_name:codex", "command_regex:app-server"],
	      risk_rank: 1,
	      acknowledged: false,
      can_acknowledge: true,
      explanation: "latest checkpoint over warning threshold",
    },
    {
      key: "claude:ce35bba6-88fb-40b7-a6be-c57fd389ba6a",
      id: "ce35bba6-88fb-40b7-a6be-c57fd389ba6a",
      provider: "claude",
      state: "idle",
      activity_state: "idle",
      process_state: "running",
      usage_state: "quiet",
      action_state: "none",
      actionable: false,
      project: "daybook",
      cwd: "/Users/phaedrus/Documents/daybook",
      models: ["claude-opus-4-7"],
      last_seen_at: now,
      last_usage_at: now,
      calls: 3,
      latest_turn_tokens: 55_323,
      total_tokens: 153_388,
      correlated_agent_id: "claude-code",
      correlated_pid: 18548,
      correlated_process_started_at: now,
      correlation_reason: "provider+cwd",
	      correlation_score: 125,
	      confidence: 55,
	      risk_rank: 4,
	      acknowledged: false,
      can_acknowledge: false,
      explanation: "no usage in current window",
    },
    {
      key: "codex:019e4699-7205-77d2-911a-df17ea989b00",
      id: "019e4699-7205-77d2-911a-df17ea989b00",
      provider: "codex",
      state: "idle-high",
      activity_state: "idle",
      process_state: "no-process",
      usage_state: "quiet-high",
      action_state: "none",
      actionable: false,
      project: "chronicle",
      cwd: "/Users/phaedrus/Documents/Codex/2026-05-20/use-chronicle",
      last_seen_at: now,
      last_usage_at: now,
      calls: 111,
	      latest_turn_tokens: 202_866,
	      total_tokens: 13_437_768,
	      risk_rank: 3,
	      acknowledged: false,
      can_acknowledge: false,
      explanation: "large historical turn, not currently spending",
    },
  ],
  turns: [
    {
      id: "turn-1",
      session_key: "codex:019e4bf7-6412-748a-b900-1df04db3f220",
      session_id: "019e4bf7-6412-748a-b900-1df04db3f220",
      provider: "codex",
      at: now,
      model: "gpt-5.3-codex",
      input_tokens: 200_000,
      cached_input_tokens: 350_000,
      cache_creation_input_tokens: 10_000,
      output_tokens: 70_000,
      total_tokens: 620_000,
      cumulative_tokens: 3_500_000,
      source: "codex",
    },
    {
      id: "turn-2",
      session_key: "claude:ce35bba6-88fb-40b7-a6be-c57fd389ba6a",
      session_id: "ce35bba6-88fb-40b7-a6be-c57fd389ba6a",
      provider: "claude",
      at: now,
      model: "claude-opus-4-7",
      input_tokens: 44_100,
      output_tokens: 11_223,
      total_tokens: 55_323,
      cumulative_tokens: 153_388,
      source: "claude",
    },
  ],
};

export const demoConfig: ConfigView = {
  path: "/Users/phaedrus/Library/Application Support/curb/config.yaml",
  machine_id: "machine_demo",
  mode: "alert",
  usage_enabled: true,
  warn_turn_tokens: 1_000_000,
  kill_turn_tokens: 3_000_000,
  usage_window_seconds: 900,
  usage_scan_seconds: 5,
  lookback_seconds: 86_400,
  process_warn_seconds: 5400,
  process_kill_seconds: 7200,
  ack_extension_seconds: 1800,
  local_notifications: true,
  ledger_forward_url: "",
  agents: [
    {
      id: "codex-desktop-worker",
      label: "Codex Desktop Worker",
      family: "codex",
      kind: "process",
      terminates: true,
      description: "worker process; eligible for enforcement",
    },
    {
      id: "claude-code",
      label: "Claude Code",
      family: "claude",
      kind: "process",
      terminates: true,
      description: "worker process; eligible for enforcement",
    },
    {
      id: "codex-desktop",
      label: "Codex Desktop",
      family: "codex",
      kind: "app",
      terminates: false,
      description: "app or shell process; visibility only",
    },
  ],
};

export const demoAlerts: AlertView[] = [
  {
    severity: "warn",
    label: "warning",
    category: "warning",
    seq: 42,
    at: now,
    agent_id: "codex-desktop-worker",
    provider: "codex",
    mode: "alert",
    message: "codex session 019e...f220 latest checkpoint used 620k tokens (total 3.5M in 33 calls)",
    cwd: "/Users/phaedrus/Development/curb",
    session_key: "codex:019e4bf7-6412-748a-b900-1df04db3f220",
    session_id: "019e4bf7-6412-748a-b900-1df04db3f220",
    actionable: false,
    can_acknowledge: true,
    explanation: "Usage or runtime crossed the warning policy.",
  },
  {
    severity: "watch",
    label: "would stop",
    category: "would_stop",
    seq: 41,
    at: now,
    agent_id: "codex-cli",
    provider: "codex",
    mode: "alert",
    message: "codex session 019e...b00 latest checkpoint used 3.2M tokens (alert mode; no process stopped)",
    cwd: "/Users/phaedrus/Development/gradient",
    session_id: "019e4699-7205-77d2-911a-df17ea989b00",
    actionable: false,
    can_acknowledge: false,
    explanation: "Alert mode: Curb would stop this correlated worker in enforcement mode.",
  },
];
